networks:
  sigue-adelante-radio:
    external: true

services:
  stream-backend:
    container_name: sar-stream-backend
    image: sar-stream-backend:1.0.0
    build: .
    ports:
      - "6000:80/tcp"
    restart: always
    volumes:
      - ~/SigueAdelanteRadio/posts/temp:/usr/app/generated/temp
    networks:
      - sigue-adelante-radio
    environment:
      PORT: 80
      DATABASE_URL: $DATABASE_URL

